### ISSUE TITLE
Please translate README.md

### ISSUE THREAD

**Issue by Hvass-Labs** [Hvass-Labs/TensorFlow-Tutorials-Chinese#2]
Please translate the README.md file as well. I have made a suggestion below for how the header could look.

I just made some changes to the README the other day about how to run this in Google Colab, see: https://github.com/Hvass-Labs/TensorFlow-Tutorials/blob/master/README.md

----

# TensorFlow Tutorials

Original repository on GitHub: [中文](https://github.com/Hvass-Labs/TensorFlow-Tutorials-Chinese) / [English](https://github.com/Hvass-Labs/TensorFlow-Tutorials)

Original author is [Magnus Erik Hvass Pedersen](http://www.hvass-labs.org)

中文翻译 [thrillerist](https://github.com/thrillerist) / [ZhouGeorge](https://github.com/ZhouGeorge)

## Introduction (Make a Chinese translation of all this English text)

* These tutorials are intended for beginners in Deep Learning and TensorFlow.
* Each tutorial covers a single topic.
* The source-code is well-documented.
* There is an [English YouTube video](https://www.youtube.com/playlist?list=PL9Hr9sNUjfsmEu1ZniY0XpHSzl5uihcXZ) for each tutorial.

## Tutorials

1. 简单线性模型 ([Notebook](https://github.com/Hvass-Labs/TensorFlow-Tutorials-Chinese/blob/master/01_Simple_Linear_Model_CN.ipynb)) ([Google Colab](https://colab.research.google.com/github/Hvass-Labs/TensorFlow-Tutorials-Chinese/blob/master/01_Simple_Linear_Model_CN.ipynb))

(...)

**Comment by ZhouGeorge** [comment]
@Hvass-Labssorry Sorry for the late reply,I'm a little busy recently. I have translated the file in my repo，then i will update the Chinese version before uploading.

**Comment by Hvass-Labs** [comment]
@ZhouGeorge I have updated your Chinese version of the README.md file with the correct links to this Chinese repo.

I have also slightly updated the README.md file in my original repo, you can see the diff here: https://github.com/Hvass-Labs/TensorFlow-Tutorials/commit/48525854f0552a2ce8f9bf4ee58d62de96d06708 Because some people were confused about downloading and installing the tutorials, so I merged those two sections. I did not really write any new text, I just re-arranged those two sections a bit. You can update the Chinese version if you want and if you have the time.

**Comment by lcbowling** [comment]
In  the section of the  ensemble learingCN，there is a problem: AttributeError: module 'tensorflow.python.ops.variable_scope' has no attribute '_VARSCOPE_KEY'.Could you tell how to solve it ?

**Comment by lcbowling** [comment]
![image](https://user-images.githubusercontent.com/14917966/45914188-ec504480-be73-11e8-8c1d-1fcdab14b9ba.png)
