### ISSUE TITLE
some question about Machine_Translation 

### ISSUE THREAD

**Issue by kewen119** [Hvass-Labs/TensorFlow-Tutorials-Chinese#5]
@Hvass-Labs Hi, thx a lot about your job! It helps me a lot. Here is my question:  while I was doing my own machine translation.  Because the last layer of the decoder is a dense layer, and the shape of the decoder output layer would be like [batch_size,sequence_len,num_words(which is 10,000)] but when training the model an error occured: the shape of y_pred and y_true does not match. The shape of y_pred is exactly the shape of the decoder output layer, but the shape of y_true is  [batch_size,sequence_len]. So how can I fix this bug, please? THX a million, and Merry Christmas!

**Comment by Hvass-Labs** [comment]
I do not maintain this fork of the project. It is only for the Chinese translation.

I guess you are using your own data or have made some modifications to the code. I don't give support in either case.

But I do wish you a Merry Christmas and Happy New Year :-)
