### ISSUE TITLE
do you have a QQ group? 是否有一个QQ群？

### ISSUE THREAD

**Issue by jobsfan** [Hvass-Labs/TensorFlow-Tutorials-Chinese#6]
why not run a QQ group for the followers? It will be much more fun when learning tensorflow.

**Comment by Hvass-Labs** [comment]
Is QQ group some kind of Chinese Internet chat-room?

You are very welcome to make such a QQ group. But I do not speak Chinese, and I don't think the Chinese translator of these tutorials has much time to tutor people directly.

**Comment by jobsfan** [comment]
yes! It something like a Chat-room. It is a software based instead of the webpage based.
I have a very small QQ group with max 200 person limit.
The QQ group number is **568056084**

In China here, QQ group and we-chat group is very popular.
Also the we-chat group
![mmqrcode1555053826012](https://user-images.githubusercontent.com/3395025/56019507-645e5900-5d37-11e9-857d-a50f8e6c8640.png)
The above qrcode works within 7 days.

**Comment by qq-877238720** [comment]
imagecolortransparent 这个函数无效，请问是什么情况？
